# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60d11adaede0796d62bd892b631233ebd00747120e36cf10c93defed30f92d2591d122b3af865279ec1cbdbc8ef8f3dc6a8845ac585e2a655e9aaf28d16e4a87

test:
  secret_key_base: fce3c9d7b581131977e02a0bfb9a87ddf349ef3b1e1dbe8525650050028e08819e182fba5ba081c5338d8fbf5af00852f11add5f72242a4d352a22dd9d842b99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
